service: serverless-aws-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:730193062599:table/TodoTable

functions:
  addTodo:
    handler: src/todo/addTodo.handler
    events:
      - httpApi:
          path: /
          method: post
  fetchTodos:
    handler: src/todo/fetchTodos.handler
    events:
      - httpApi:
          path: /todos
          method: get
  fetchTodo:
    handler: src/todo/fetchTodo.handler
    events:
      - httpApi:
          path: /todo/{id}
          method: get
  updateTodo:
    handler: src/todo/updateTodo.handler
    events:
      - httpApi:
          path: /todo/{id}
          method: put 
  insertIntoMongoDB:
    handler: src/insertIntoMongoDB.handler
    events:
      - httpApi:
          path: /insertIntoMongoDB
          method: post
  WrapperLambdaFunction:
    handler: src/stepFunction/WrapperLambdaFunction.handler
    events:
      - httpApi:
          path: /WrapperLambdaFunction
          method: get
  SecondLambdaFunction:
    handler: src/stepFunction/SecondLambdaFunction.handler
    events:
      - httpApi:
          path: /SecondLambdaFunction
          method: get
  ThirdLambdaFunction:
    handler: src/stepFunction/ThirdLambdaFunction.handler
    events:
      - httpApi:
          path: /ThirdLambdaFunction
          method: get 
  FourthLambdaFunction:
    handler: src/stepFunction/FourthLambdaFunction.handler
    events:
      - httpApi:
          path: /FourthLambdaFunction
          method: get          

  # StateMachine:
  #   Comment: "An example Step Functions state machine with parallel Lambdas"
  #   StartAt: WrapperLambda
    # States:
    #   WrapperLambda:
    #     Type: Task
    #     Resource: arn:aws:lambda:us-east-1:730193062599:function:serverless-aws-lambda-dev-WrapperLambdaFunction
    #     Next: ParallelLambdas
    #   ParallelLambdas:
    #     Type: Parallel
    #     Branches:
    #       - StartAt: SecondLambda
    #         States:
    #           SecondLambda:
    #             Type: Task
    #             Resource: arn:aws:lambda:us-east-1:730193062599:function:serverless-aws-lambda-dev-SecondLambdaFunction
    #             End: true
    #       - StartAt: ThirdLambda
    #         States:
    #           ThirdLambda:
    #             Type: Task
    #             Resource: arn:aws:lambda:us-east-1:730193062599:function:serverless-aws-lambda-dev-ThirdLambdaFunction
    #             End: true
    #     End: true
    #   WaitForCompletion:
    #     Type: Task
    #     Resource: arn:aws:lambda:us-east-1:730193062599:function:serverless-aws-lambda-dev-FourthLambdaFunction
    #     End: true


resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TodoTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
         - AttributeName: id
           KeyType: HASH
  MyStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      DefinitionString:
        Comment: "My Step Functions State Machine"
        StartAt: WrapperLambda
        States:
          WrapperLambda:
            Type: Task
            Resource: arn:aws:lambda:us-east-1:730193062599:function:serverless-aws-lambda-dev-WrapperLambdaFunction
            Next: ParallelLambdas
          ParallelLambdas:
            Type: Parallel
            Branches:
              - StartAt: SecondLambda
        States:
          SecondLambda:
            Type: Task
            Resource: arn:aws:lambda:us-east-1:730193062599:function:serverless-aws-lambda-dev-SecondLambdaFunction
            End: true
              - StartAt: ThirdLambda
        States:
          ThirdLambda:
            Type: Task
            Resource: arn:aws:lambda:us-east-1:730193062599:function:serverless-aws-lambda-dev-ThirdLambdaFunction
            End: true
        End: true
      WaitForCompletion:
        Type: Task
        Resource: arn:aws:lambda:us-east-1:730193062599:function:serverless-aws-lambda-dev-FourthLambdaFunction
        End: true




